name: Sass

on:
  push:
    branches:
      - production

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps: 
      - name: Delete previous compiled files
        run: rm assets/css/styles.css
      
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.3
        with:
          source: assets/sass/styles.scss
          destination: assets/css/styles.css
